spring:
  format:
    style: google
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/tournament_db
    username: ${MYSQL_USER:tournament_admin}
    password: ${MYSQL_PASSWORD:tournament@2023}
  sql:
    init:
      mode: always

jwt:
  secret: 6a8e1e15d6b7892e8e6f13d7bc54b6c07d398c57923c8b2044973203e7023704
  expirationTime: 86400000
  tokenPrefix: 'Bearer '
  authorizationHeaderString: Authorization
  headerSkipLength: 7

eureka:
  client:
    service-url:
      defaultZone: http://tourni-discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        step: 10s # Export interval set to 10 seconds
  tracing:
    sampling:
      probability: 1.0


  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

